[
    "dangdut",
    "filthstep",
    "free jazz",
    "madchester",
    "chicago blues",
    "downtempo",
    "skweee",
    "turntablism",
    "speedcore",
    "crust punk",
    "banda",
    "freak folk",
    "ebm",
    "chicago soul",
    "noise pop",
    "punk blues",
    "chalga",
    "singer-songwriter",
    "industrial metal",
    "stoner metal",
    "italian disco",
    "doom metal",
    "bubblegum dance",
    "nu jazz",
    "modern classical",
    "jam band",
    "canterbury scene",
    "mambo",
    "piedmont blues",
    "balkan brass",
    "reggae",
    "soukous",
    "mathcore",
    "calypso",
    "dream pop",
    "dub",
    "pop rock",
    "choral",
    "trance",
    "orchestral",
    "jug band",
    "bossa nova",
    "classical guitar",
    "russian pop",
    "pop rap",
    "zeuhl",
    "neue deutsche harte",
    "classical",
    "makossa",
    "nu gaze",
    "rockabilly",
    "bangla",
    "teen pop",
    "speed metal",
    "moombahton",
    "stoner rock",
    "j-rock",
    "dance-punk",
    "old school hip hop",
    "folk metal",
    "irish folk",
    "celtic",
    "progressive metal",
    "malaysian pop",
    "screamo",
    "bluegrass",
    "finnish hip hop",
    "wonky",
    "neo-psychedelic",
    "andean",
    "zouglou",
    "hip house",
    "anti-folk",
    "europop",
    "southern gospel",
    "children's music",
    "j-idol",
    "goregrind",
    "delta blues",
    "visual kei",
    "hungarian pop",
    "exotica",
    "czech folk",
    "belgian rock",
    "rock-and-roll",
    "kwaito",
    "psychobilly",
    "zouk",
    "beatdown",
    "opera",
    "emo",
    "dancehall",
    "persian pop",
    "tech house",
    "thai pop",
    "manele",
    "freestyle",
    "boogaloo",
    "g funk",
    "jump blues",
    "viking metal",
    "math pop",
    "memphis blues",
    "operatic pop",
    "ethereal wave",
    "ska punk",
    "chanson",
    "gangster rap",
    "progressive rock",
    "country blues",
    "folk rock",
    "detroit techno",
    "black death",
    "acoustic blues",
    "power electronics",
    "intelligent dance music",
    "memphis soul",
    "electro house",
    "dance pop",
    "c86",
    "post-grunge",
    "drum and bass",
    "fado",
    "desi",
    "power metal",
    "avantgarde metal",
    "german punk",
    "dutch house",
    "schranz",
    "martial industrial",
    "rap metal",
    "danish pop",
    "cantopop",
    "pop punk",
    "blues",
    "neofolk",
    "outlaw country",
    "r&b",
    "big band",
    "rock steady",
    "peruvian rock",
    "mariachi",
    "happy hardcore",
    "technical death metal",
    "brazilian punk",
    "swamp blues",
    "drone",
    "djent",
    "jazz funk",
    "pagode",
    "trip hop",
    "piano blues",
    "electronic",
    "thrash metal",
    "video game music",
    "space rock",
    "noise rock",
    "bounce",
    "tribal house",
    "blues-rock",
    "soul jazz",
    "glam rock",
    "west coast rap",
    "dance rock",
    "dark ambient",
    "classic russian rock",
    "fourth world",
    "power noise",
    "horror punk",
    "nu disco",
    "spanish indie pop",
    "folk",
    "psychedelic rock",
    "sludge metal",
    "latin pop",
    "cumbia",
    "post-hardcore",
    "kompa",
    "acid house",
    "russian rock",
    "liquid funk",
    "hardcore hip hop",
    "new beat",
    "nueva cancion",
    "show tunes",
    "roots reggae",
    "rap",
    "neo classical metal",
    "south african jazz",
    "avant-garde",
    "electroclash",
    "brazilian hip hop",
    "bhangra",
    "post-punk",
    "christian alternative rock",
    "vocal jazz",
    "indian classical",
    "polka",
    "gabba",
    "irish rock",
    "art rock",
    "east coast hip hop",
    "new age",
    "sega",
    "folk-pop",
    "kraut rock",
    "cool jazz",
    "punjabi",
    "latin",
    "gospel",
    "broken beat",
    "new jack swing",
    "minimal",
    "rap rock",
    "choro",
    "latin alternative",
    "piano rock",
    "chicago house",
    "glam metal",
    "swiss rock",
    "smooth jazz",
    "symphonic black metal",
    "alternative country",
    "baile funk",
    "surf music",
    "bebop",
    "stride",
    "indonesian pop",
    "roots rock",
    "soundtrack",
    "cello",
    "quiet storm",
    "christian music",
    "hard house",
    "electro-industrial",
    "garage rock",
    "taiwanese pop",
    "southern rock",
    "bolero",
    "string quartet",
    "math rock",
    "brutal death metal",
    "symphonic rock",
    "neo soul",
    "lo-fi",
    "indietronica",
    "lounge",
    "japanoise",
    "hiplife",
    "french rock",
    "british folk",
    "christian metal",
    "hard rock",
    "louisiana blues",
    "power pop",
    "meditation",
    "progressive bluegrass",
    "jazz",
    "worship",
    "christian hip hop",
    "drill and bass",
    "chill-out",
    "futurepop",
    "barbershop",
    "brill building pop",
    "death core",
    "reggaeton",
    "britpop",
    "thrash core",
    "crunk",
    "electric blues",
    "skate punk",
    "melodic death metal",
    "twee pop",
    "brazilian pop music",
    "flamenco",
    "melodic hardcore",
    "progressive psytrance",
    "alternative hip hop",
    "latin jazz",
    "salsa",
    "renaissance",
    "deep house",
    "house",
    "southern hip hop",
    "classic rock",
    "latin metal",
    "rumba",
    "power violence",
    "native american",
    "protopunk",
    "argentine rock",
    "glitch hop",
    "turbo folk",
    "funeral doom",
    "deathgrind",
    "vocaloid",
    "norwegian pop",
    "vallenato",
    "suomi rock",
    "new orleans jazz",
    "ccm",
    "freakbeat",
    "highlife",
    "indie pop",
    "breakbeat",
    "industrial rock",
    "brass band",
    "progressive house",
    "aggrotech",
    "luk thung",
    "traditional folk",
    "skiffle",
    "ragtime",
    "neo-progressive",
    "big beat",
    "bubblegum pop",
    "dubstep",
    "texas country",
    "album rock",
    "experimental rock",
    "cuban rumba",
    "eurobeat",
    "jangle pop",
    "christian rock",
    "british invasion",
    "samba",
    "british blues",
    "bachata",
    "dark wave",
    "hip hop",
    "black metal",
    "christian hardcore",
    "lovers rock",
    "adult standards",
    "afrobeat",
    "bass music",
    "slow core",
    "neoclassical",
    "shoegaze",
    "motown",
    "metal",
    "metalcore",
    "new weird america",
    "hardcore techno",
    "zydeco",
    "chiptune",
    "texas blues",
    "folk punk",
    "traditional blues",
    "uplifting trance",
    "grime",
    "digital hardcore",
    "doo-wop",
    "funk metal",
    "german hip hop",
    "chamber pop",
    "soul blues",
    "outsider",
    "avant-garde jazz",
    "soul",
    "schlager",
    "gothic metal",
    "symphonic metal",
    "techno",
    "portuguese rock",
    "northern soul",
    "neurofunk",
    "acid jazz",
    "tejano",
    "hardstyle",
    "throat singing",
    "funk",
    "indie rock",
    "western swing",
    "grunge",
    "christian punk",
    "post rock",
    "straight edge",
    "new orleans blues",
    "sertanejo",
    "groove metal",
    "capoeira",
    "experimental",
    "j-pop",
    "ska",
    "merseybeat",
    "arab pop",
    "uk garage",
    "grindcore",
    "filmi",
    "world",
    "nu metal",
    "hardcore",
    "funk rock",
    "eurodance",
    "melodic metalcore",
    "mpb",
    "industrial",
    "celtic rock",
    "turkish pop",
    "vietnamese pop",
    "country gospel",
    "underground hip hop",
    "k-pop",
    "hawaiian",
    "punk",
    "rock catala",
    "k-rock",
    "disco",
    "minimal techno",
    "vocal house",
    "future garage",
    "soca",
    "new romantic",
    "nordic folk",
    "electro",
    "breakcore",
    "rock en espanol",
    "synthpop",
    "chillwave",
    "merengue",
    "jazz fusion",
    "reggae rock",
    "alternative dance",
    "dirty south rap",
    "hard bop",
    "comedy",
    "country rock",
    "cowpunk",
    "indie folk",
    "gothic rock",
    "country",
    "volksmusik",
    "glitch",
    "contemporary jazz",
    "free improvisation",
    "swing",
    "jungle",
    "alternative metal",
    "ambient",
    "southern soul",
    "tango",
    "crossover thrash",
    "pop emo",
    "hard trance",
    "a cappella",
    "psychedelic trance",
    "gypsy jazz",
    "shibuya-kei",
    "alternative rock",
    "boogie-woogie",
    "rock",
    "new wave",
    "harp",
    "italian pop",
    "death metal",
    "ranchera",
    "soft rock",
    "cabaret",
    "neo-singer-songwriter",
    "christmas",
    "j-punk",
    "alternative pop",
    "coverchill",
    "swedish pop",
    "latvian pop",
    "current",
    "harmonica blues",
    "japanese psychedelic",
    "australian pop",
    "nu-cumbia",
    "neo-pagan",
    "dark black metal",
    "wind ensemble",
    "hot adult contemporary",
    "telugu",
    "jazz orchestra",
    "duranguense",
    "nepali",
    "minimal wave",
    "kuduro",
    "microhouse",
    "tamil",
    "slovenian rock",
    "mbalax",
    "new rave",
    "christian dance",
    "latin christian",
    "brutal deathcore",
    "tekno",
    "tin pan alley",
    "italian indie pop",
    "classic funk rock",
    "deeper house",
    "more thrash metal",
    "grave wave",
    "marching band",
    "punk christmas",
    "indian rock",
    "bouncy house",
    "atmospheric post rock",
    "experimental psych",
    "australian hip hop",
    "azonto",
    "oratory",
    "more tech house",
    "austindie",
    "axe",
    "chaotic hardcore",
    "deep soul house",
    "underground rap",
    "contemporary post-bop",
    "enka",
    "chr",
    "eurovision",
    "electroacoustic improvisation",
    "tropical",
    "mexican son",
    "country christmas",
    "scottish rock",
    "indie christmas",
    "melodic hard rock",
    "kirtan",
    "darkstep",
    "ninja",
    "anime",
    "venezuelan rock",
    "estonian pop",
    "vaporwave",
    "pop",
    "nu skool breaks",
    "lds",
    "spanish punk",
    "pop christmas",
    "retro metal",
    "stomp and holler",
    "australian alternative rock",
    "dutch hip hop",
    "reggae fusion",
    "warm drone",
    "trapstep",
    "hard glam",
    "uk post-punk",
    "comic",
    "german pop",
    "vegan straight edge",
    "acousmatic",
    "afrobeats",
    "alternative emo",
    "balearic",
    "yugoslav rock",
    "old-time",
    "pipe band",
    "acoustic pop",
    "stomp pop",
    "gamelan",
    "chinese indie rock",
    "icelandic pop",
    "zim",
    "merengue urbano",
    "deep funk",
    "polish hip hop",
    "sexy",
    "filter house",
    "opm",
    "dutch pop",
    "polish pop",
    "chill lounge",
    "footwork",
    "hurban",
    "mellow gold",
    "c-pop",
    "fingerstyle",
    "slam death metal",
    "lo star",
    "guidance",
    "garage pop",
    "neo-industrial rock",
    "pakistani pop",
    "electro swing",
    "baroque",
    "demoscene",
    "classical piano",
    "urban contemporary",
    "benga",
    "tribute",
    "christian christmas",
    "violin",
    "classic chinese pop",
    "ambient idm",
    "ethiopian pop",
    "more indie pop",
    "underground power pop",
    "jazz christmas",
    "spanish hip hop",
    "latin hip hop",
    "trap music",
    "la indie",
    "neue deutsche welle",
    "brazilian gospel",
    "hot",
    "ecuadoria",
    "afrikaans",
    "basque rock",
    "more melodic death metal",
    "modern country rock",
    "oi",
    "atmospheric black metal",
    "chinese traditional",
    "shiver pop",
    "riot grrrl",
    "canadian indie",
    "grupera",
    "classical period",
    "gothic alternative",
    "norwegian jazz",
    "austropop",
    "easy listening",
    "musique concrete",
    "finnish hardcore",
    "romanian pop",
    "malagasy folk",
    "serialism",
    "swedish hip hop",
    "belly dance",
    "psychill",
    "medieval",
    "quebecois",
    "hyphy",
    "doomcore",
    "classical christmas",
    "soul christmas",
    "nwobhm",
    "african percussion",
    "jazz blues",
    "hi nrg",
    "liedermacher",
    "celtic christmas",
    "workout",
    "k-indie",
    "j-rap",
    "traditional country",
    "french hip hop",
    "rai",
    "gothic symphonic metal",
    "christmas product",
    "judaica",
    "indie shoegaze",
    "heavy christmas",
    "nu age",
    "neo-synthpop",
    "psych gaze",
    "disco house",
    "forro",
    "klezmer",
    "arab folk",
    "shimmer pop",
    "world fusion",
    "nashville sound",
    "chicano rap",
    "spanish pop",
    "swedish indie pop",
    "dutch rock",
    "progressive electro house",
    "welsh rock",
    "sxsw",
    "adult album alternative",
    "witch house",
    "downtempo fusion",
    "qawwali",
    "kannada",
    "german oi",
    "albanian pop",
    "shimmer psych",
    "french pop",
    "mashup",
    "breaks",
    "hard alternative",
    "pagan black metal",
    "screamo punk",
    "contemporary classical",
    "ye ye",
    "israeli rock",
    "slovak pop",
    "lithumania",
    "modern blues",
    "post-post-hardcore",
    "power blues-rock",
    "japanese standards",
    "swedish punk",
    "pub rock",
    "japanese traditional",
    "jerk",
    "jazz metal",
    "power-pop punk",
    "gujarati",
    "mandopop",
    "russian punk",
    "malayalam",
    "j-metal",
    "neurostep",
    "steampunk",
    "viral pop",
    "faroese pop",
    "speed garage",
    "entehno",
    "russian hip hop",
    "juggalo",
    "chilean rock",
    "drumfunk",
    "r-neg-b",
    "mexican indie",
    "french indie pop",
    "nintendocore",
    "hands up",
    "riddim",
    "indian pop",
    "no wave",
    "poetry",
    "k-hop",
    "discovery",
    "world christmas",
    "classic garage rock",
    "folk christmas",
    "lilith",
    "illbient",
    "medieval rock",
    "new tribe",
    "german indie",
    "ukrainian rock",
    "hardcore punk",
    "hardcore breaks",
    "abstract hip hop",
    "trova",
    "finnish pop",
    "j-alt",
    "vienna indie",
    "kiwi rock",
    "j-dance",
    "cantautor",
    "talent show",
    "norteno",
    "spoken word",
    "jump up",
    "nl folk",
    "brostep",
    "polish reggae",
    "brazilian indie",
    "velha guarda",
    "gothic americana",
    "latin christmas",
    "orgcore",
    "regional mexican",
    "japanese r&b",
    "kizomba",
    "trance hop",
    "progressive trance",
    "post-metal",
    "neo-trad metal",
    "dreamo",
    "mande pop",
    "early music",
    "laiko",
    "electro trash",
    "croatian pop",
    "romantic",
    "melodic progressive metal",
    "more classical piano",
    "african rock",
    "italian hip hop",
    "contemporary country",
    "acid techno",
    "post-disco",
    "dub techno",
    "fallen angel",
    "canadian pop"
]
